const comuni = [
  { name: 'Affile', value: 'affile' },
  { name: 'Agosta', value: 'agosta' },
  { name: 'Albano Laziale', value: 'albano+laziale' },
  { name: 'Allumiere', value: 'allumiere' },
  { name: 'Anguillara Sabazia', value: 'anguillara+sabazia' },
  { name: 'Anticoli Corrado', value: 'anticoli+corrado' },
  { name: 'Anzio', value: 'anzio' },
  { name: 'Arcinazzo Romano', value: 'arcinazzo+romano' },
  { name: 'Ariccia', value: 'ariccia' },
  { name: 'Arsoli', value: 'arsoli' },
  { name: 'Artena', value: 'artena' },
  { name: 'Bellegra', value: 'bellegra' },
  { name: 'Bracciano', value: 'bracciano' },
  { name: 'Camerata Nuova', value: 'camerata+nuova' },
  { name: 'Campagnano di Roma', value: 'campagnano+di+roma' },
  { name: 'Canale Monterano', value: 'canale+monterano' },
  { name: 'Canterano', value: 'canterano' },
  { name: 'Capena', value: 'capena' },
  { name: 'Capranica Prenestina', value: 'capranica+prenestina' },
  { name: 'Carpineto Romano', value: 'carpineto+romano' },
  { name: 'Casape', value: 'casape' },
  { name: 'Castel Gandolfo', value: 'castel+gandolfo' },
  { name: 'Castel Madama', value: 'castel+madama' },
  { name: 'Castelnuovo di Porto', value: 'castelnuovo+di+porto' },
  { name: 'Cave', value: 'cave' },
  { name: 'Cerreto Laziale', value: 'cerreto+laziale' },
  { name: 'Cervara di Roma', value: 'cervara+di+roma' },
  { name: 'Cerveteri', value: 'cerveteri' },
  { name: 'Ciciliano', value: 'ciciliano' },
  { name: 'Cineto Romano', value: 'cineto+romano' },
  { name: 'Civitavecchia', value: 'civitavecchia' },
  { name: 'Civitella San Paolo', value: 'civitella+san+paolo' },
  { name: 'Colleferro', value: 'colleferro' },
  { name: 'Colonna', value: 'colonna' },
  { name: 'Fiano Romano', value: 'fiano+romano' },
  { name: 'Filacciano', value: 'filacciano' },
  { name: 'Fiumicino', value: 'fiumicino' },
  { name: 'Fonte Nuova', value: 'fonte+nuova' },
  { name: 'Formello', value: 'formello' },
  { name: 'Frascati', value: 'frascati' },
  { name: 'Fiumicino', value: 'fiumicino' },
  { name: 'Fonte Nuova', value: 'fonte+nuova' },
  { name: 'Gavignano Sabino', value: 'gavignano+sabino' },
  { name: 'Genazzano', value: 'genazzano' },
  { name: 'Genzano di Roma', value: 'genzano+di+roma' },
  { name: 'Gerano', value: 'gerano' },
  { name: 'Gorga', value: 'gorga' },
  { name: 'Guidonia Montecelio', value: 'guidonia+montecelio' },
  { name: 'Grottaferrata', value: 'grottaferrata' },
  { name: 'Jenne', value: 'jenne' },
  { name: 'Labico', value: 'labico' },
  { name: 'Lanuvio', value: 'lanuvio' },
  { name: 'Lariano', value: 'lariano' },
  { name: 'Licenza', value: 'licenza' },
  { name: 'Magliano Romano', value: 'magliano+romano' },
  { name: 'Mandela', value: 'mandela' },
  { name: 'Manziana', value: 'manziana' },
  { name: 'Marano Equo', value: 'marano+equo' },
  { name: 'Marcellina', value: 'marcellina' },
  { name: 'Marino', value: 'marino' },
  { name: 'Mazzano Romano', value: 'mazzano+romano' },
  { name: 'Mentana', value: 'mentana' },
  { name: 'Monte Compatri', value: 'monte+compatri' },
  { name: 'Monteflavio', value: 'monteflavio' },
  { name: 'Montelanico', value: 'montelanico' },
  { name: 'Montelibretti', value: 'montelibretti' },
  { name: 'Monte Porzio Catone', value: 'monte+porzio+catone' },
  { name: 'Monterotondo', value: 'monterotondo' },
  { name: 'Montorio Romano', value: 'montorio+romano' },
  { name: 'Moricone', value: 'moricone' },
  { name: 'Morlupo', value: 'morlupo' },
  { name: 'Nazzano', value: 'nazzano' },
  { name: 'Nemi', value: 'nemi' },
  { name: 'Nerola', value: 'nerola' },
  { name: 'Nettuno', value: 'nettuno' },
  { name: 'Olevano Romano', value: 'olevano+romano' },
  { name: 'Palestrina', value: 'palestrina' },
  { name: 'Palombara Sabina', value: 'palombara+sabina' },
  { name: 'Percile', value: 'percile' },
  { name: 'Pisoniano', value: 'pisoniano' },
  { name: 'Poli', value: 'poli' },
  { name: 'Pomezia', value: 'pomezia' },
  { name: 'Pomezia', value: 'pomezia' },
  { name: 'Riano', value: 'riano' },
  { name: 'Rignano Flaminio', value: 'rignano+flaminio' },
  { name: 'Riofreddo', value: 'riofreddo' },
  { name: 'Rocca Canterano', value: 'rocca+canterano' },
  { name: 'Rocca Priora', value: 'rocca+priora' },
  { name: 'Rocca Santo Stefano', value: 'rocca+santo+stefano' },
  { name: 'Roccagiovine', value: 'roccagiovine' },
  { name: 'Roiate', value: 'roiate' },
  { name: 'Roma', value: 'roma' },
  { name: 'Roviano', value: 'roviano' },
  { name: 'Sacrofano', value: 'sacrofano' },
  { name: 'Sambuci', value: 'sambuci' },
  { name: 'San Gregorio da Sassola', value: 'san+gregorio+da+sassola' },
  { name: 'San Polo dei Cavalieri', value: 'san+polo+dei+cavalieri' },
  { name: 'Santa Marinella', value: 'santa+marinella' },
  { name: `Sant'Angelo Romano`, value: `sant'angelo+romano` },
  { name: `Sant'Oreste`, value: `sant'oreste` },
  { name: 'Scandriglia', value: 'scandriglia' },
  { name: 'Sedico', value: 'sedico' },
  { name: 'Segni', value: 'segni' },
  { name: 'Subiaco', value: 'subiaco' },
  { name: 'Tivoli', value: 'tivoli' },
  { name: 'Tolfa', value: 'tolfa' },
  { name: 'Torrita Tiberina', value: 'torrita+tiberina' },
  { name: 'Trevignano Romano', value: 'trevignano+romano' },
  { name: 'Vallepietra', value: 'vallepietra' },
  { name: 'Vallinfreda', value: 'vallinfreda' },
  { name: 'Valmontone', value: 'valmontone' },
  { name: 'Velletri', value: 'velletri' },
  { name: 'Vicovaro', value: 'vicovaro' },
  { name: 'Vivaro Romano', value: 'vivaro+romano' },
  { name: 'Zagarolo', value: 'zagarolo' },
]

export { comuni }
